repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.26.0
    hooks:
      - id: pyupgrade
        exclude: static|migrations
        args: [--py39-plus]
  - repo: https://github.com/rtts/djhtml
    rev: v1.5.0
    hooks:
      - id: djhtml
        exclude: (.git|node_modules)
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: static|migrations
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        exclude: static|migrations
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: static|migrations
