# Generated by Django 3.2.12 on 2022-03-31 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infohotel',
            name='enregistrer_par',
        ),
    ]
