# Generated by Django 3.2.12 on 2022-04-03 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservation',
            table=None,
        ),
    ]
