# Generated by Django 3.2.12 on 2022-03-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_infohotel_enregistrer_le'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chambre_type', models.CharField(choices=[('1', 'VIP'), ('2', 'Semi-VIP')], max_length=30)),
                ('chambre_status', models.CharField(choices=[('1', 'Disponible'), ('2', 'Non-disponible')], max_length=20)),
                ('prix', models.IntegerField()),
                ('chambre_numero', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='InfoHotel',
        ),
    ]
