# Generated by Django 3.2.12 on 2022-03-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20220331_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='chambre_status',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('non-disponible', 'Non-disponible')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='chambre_type',
            field=models.CharField(choices=[('VIP', 'VIP'), ('semi-VIP', 'Semi-VIP')], max_length=30),
        ),
    ]
