# Generated by Django 3.2.13 on 2022-06-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='chambre_numero',
            field=models.IntegerField(unique=True),
        ),
    ]
