# Generated by Django 3.2.14 on 2022-07-22 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0005_alter_chambre_chambre_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_payment', models.DateField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('reference', models.CharField(max_length=200, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation')),
            ],
        ),
    ]
