# Generated by Django 3.2.14 on 2022-08-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_reservation_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bill_reference',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
