# Generated by Django 3.2.14 on 2022-08-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_payment_bill_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_status',
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
